apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-backend
  namespace: elbatt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-backend
  template:
    metadata:
      labels:
        app: chatbot-backend
    spec:
      containers:
      - name: chatbot-backend
        image: rg.fr-par.scw.cloud/elbatt/chatbot-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: GLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: glm-secrets
              key: GLM_API_KEY
        - name: GLM_BASE_URL
          valueFrom:
            secretKeyRef:
              name: glm-secrets
              key: GLM_BASE_URL
        - name: GLM_MODEL
          valueFrom:
            secretKeyRef:
              name: glm-secrets
              key: GLM_MODEL
        - name: GLM_MAX_TOKENS
          valueFrom:
            secretKeyRef:
              name: glm-secrets
              key: GLM_MAX_TOKENS
        - name: GLM_TEMPERATURE
          valueFrom:
            secretKeyRef:
              name: glm-secrets
              key: GLM_TEMPERATURE
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: OPENAI_API_KEY
        - name: OPENAI_BASE_URL
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: OPENAI_BASE_URL
        - name: CHATGPT_MODEL
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: CHATGPT_MODEL
        - name: CHATGPT_MAX_TOKENS
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: CHATGPT_MAX_TOKENS
        - name: CHATGPT_TEMPERATURE
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: CHATGPT_TEMPERATURE
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
