apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elbatt-ingress
  namespace: elbatt
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chatbot.elbatt.no
      secretName: elbatt-tls
  rules:
    - host: chatbot.elbatt.no
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chatbot-backend-service
                port:
                  number: 8000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: chatbot-backend-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatbot-frontend-service
                port:
                  number: 80
