apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elbatt-ingress
  namespace: elbatt
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: chatbot.elbatt.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatbot-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: chatbot-backend-service
            port:
              number: 8000
  - host: admin.elbatt.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: admin-backend-service
            port:
              number: 8002
