apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: elbatt
contexts:
- context:
    cluster: elbatt
    namespace: elbatt
    user: github-deployer
  name: github-deployer@elbatt
current-context: github-deployer@elbatt
users:
- name: github-deployer
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Inh3T3ZoUUVxSWZPbFF4a2dVbkx3VVI3OWwzcjZVdmZ3cjlFN1RCZUhsWGcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzU1MDM4MTk5LCJpYXQiOjE3NTQ5NTE3OTksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMDU1YWZiMTItZjQ0MS00Y2QwLWI4N2YtMzQ0Zjk5NmIxYjExIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJlbGJhdHQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ2l0aHViLWRlcGxveWVyIiwidWlkIjoiNWFkZGMzYzYtODcxYi00YTllLWFkMjMtOWMxNDYyNzJjOTc1In19LCJuYmYiOjE3NTQ5NTE3OTksInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDplbGJhdHQ6Z2l0aHViLWRlcGxveWVyIn0.aeRkeWZEAQTRWfgxJ9h6CyOQIPgWrRP9KHvSDf3WuHhWAWrftB6w83kX66dXGIJ6vGyxIrFdb5vXxYdhpcOvqdjrU-xM7xAJeMYukIp3fF_cmuQSRA0BJUsM2lmhTtQxHN3TwsInMW_rYHFK7x1UVdg9PgHYCTPMm2XbE2ZOOkSlrW-IAd2Th-l3DiJUcsEGVix_zNkB1HFx_ROvPnfXmL4vfXq4m1Z-N0yZnexOzVSrctrXEqrSGaAGPjeZTzdB8YCDdgPr7SDOCobNWYm6s3oeTCEa-EeeVI25vMiB2F0cMjGl4zZQWRqRnov3oHZQVuEhczpUrwRvWkgCQ4MAeg
