apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deployer-binding
  namespace: elbatt
subjects:
  - kind: ServiceAccount
    name: github-deployer
    namespace: elbatt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-deployer-role
