cat > k8s/rbac-github-deployer.yaml <<'YAML'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deployer
  namespace: elbatt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-deployer-role
  namespace: elbatt
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services","configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
YAML

kubectl -n elbatt apply -f k8s/rbac-github-deployer.yaml
